.PHONY: clean All

All:
	@echo "----------Building project:[ custom_Time - Debug ]----------"
	@cd "custom_Time" && "$(MAKE)" -f  "custom_Time.mk"
clean:
	@echo "----------Cleaning project:[ custom_Time - Debug ]----------"
	@cd "custom_Time" && "$(MAKE)" -f  "custom_Time.mk" clean
